---
- name: Pull and Run docker image
  hosts: all
  tasks:
    - name: Pull chvashumt2020096/calculator-devops-proj-image
      docker_image:
        name: chvashumt2020096/calculator-devops-proj-image
        source: pull
#    - name: Copy jar file to home directory
#      copy:
#        src: ./target/Lab3Junit-1.0-SNAPSHOT.jar
#        dest: ~/
#        mode: '0755'